// Generated by https://quicktype.io

export interface GithubRef {
    ref:     string;
    node_id: string;
    url:     string;
    object:  Object;
}

export interface Object {
    sha:  string;
    type: string;
    url:  string;
}

// Generated by https://quicktype.io

export interface GithubCommit {
    sha:          string;
    node_id:      string;
    url:          string;
    html_url:     string;
    author:       Author;
    committer:    Author;
    tree:         Tree;
    message:      string;
    parents:      Parent[];
    verification: Verification;
}

export interface Author {
    name:  string;
    email: string;
    date:  string;
}

export interface Parent {
    sha:      string;
    url:      string;
    html_url: string;
}

export interface Tree {
    sha: string;
    url: string;
}

// Generated by https://quicktype.io

export interface GithubTree {
    sha:       string;
    url:       string;
    tree:      Tree[];
    truncated: boolean;
    parent?: GithubTree;
}

export interface Tree {
    path:  string;
    mode:  string;
    type:  Type;
    sha:   string;
    size: number;
    url:   string;
}

export enum Type {
    Blob = "blob",
    Tree = "tree",
}

// Generated by https://quicktype.io

export interface GithubBlob {
    sha:      string;
    node_id:  string;
    size:     number;
    url:      string;
    content:  string;
    encoding: string;
}

// Generated by https://quicktype.io

export interface GithubProfile {
    login:                     string;
    id:                        number;
    node_id:                   string;
    avatar_url:                string;
    gravatar_id:               string;
    url:                       string;
    html_url:                  string;
    followers_url:             string;
    following_url:             string;
    gists_url:                 string;
    starred_url:               string;
    subscriptions_url:         string;
    organizations_url:         string;
    repos_url:                 string;
    events_url:                string;
    received_events_url:       string;
    type:                      string;
    site_admin:                boolean;
    name:                      string;
    company:                   null;
    blog:                      string;
    location:                  null;
    email:                     null;
    hireable:                  boolean;
    bio:                       string;
    public_repos:              number;
    public_gists:              number;
    followers:                 number;
    following:                 number;
    created_at:                string;
    updated_at:                string;
    private_gists:             number;
    total_private_repos:       number;
    owned_private_repos:       number;
    disk_usage:                number;
    collaborators:             number;
    two_factor_authentication: boolean;
    plan:                      Plan;
}

export interface Plan {
    name:          string;
    space:         number;
    collaborators: number;
    private_repos: number;
}

// Generated by https://quicktype.io

export interface GithubTag {
    node_id:      string;
    sha:          string;
    url:          string;
    tagger:       Tagger;
    object:       Object;
    tag:          string;
    message:      string;
    verification: Verification;
}

export interface Object {
    sha:  string;
    type: string;
    url:  string;
}

export interface Tagger {
    name:  string;
    email: string;
    date:  string;
}

export interface Verification {
    verified:  boolean;
    reason:    string;
    signature: string;
    payload:   string;
}


// Generated by https://quicktype.io

export interface GithubLimits {
    resources: Resources;
    rate:      Rate;
}

export interface Rate {
    limit:     number;
    remaining: number;
    reset:     number;
}

export interface Resources {
    core:                 Rate;
    search:               Rate;
    graphql:              Rate;
    integration_manifest: Rate;
    source_import:        Rate;
}
